### PR TITLE
Bugfix/reset accordion on destroy

### LINKED ISSUE #42: Accordion component should fully reset when destroyed
### Description
The [Accordion](https://js-toolkit.meta.fr/components/Accordion.html) component does not fully reset when destroyed. The styles added by the component are not removed. 

There is a `style="height: 0px;"` on the `data-ref="content"` which can be breaking a layout.

### How to reproduce
Init a responsive Accordion component using `withBreakpointDecorator`

### How to fix
Remove the styles when the component is `destroyed`

### PR DESCRIPTION
**Pull request by titouanmathis**
Remove styles from the AccordionItem component when it is destroyed.

Fixes #42.

### CODE REVIEW

File: src/components/Accordion/index.js [hunk 1]
```diff
@@ -55,14 +55,11 @@ export default class Accordion extends Base {
...
-    // /** @type {AccordionItem[]} */
-    // const items = await Promise.all(
-    //   this.$children.AccordionItem.map((item) =>
-    //     item instanceof Promise ? item : Promise.resolve(item)
-    //   )
-    // );
-
     this.unbindMethods = this.$children.AccordionItem.map((item, index) => {
+      if (item instanceof Promise) {
+        throw new Error('The AccordionItem component can not be used asynchronously.');
```
Comment (perruche) [inline src/components/Accordion/index.js:60]: 👍

**Review by perruche — APPROVED** [review]
